// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCarS13SzWRFvXFoVGfMRCz8FAFu1m2XY',
    appId: '1:578948566482:web:9efb6d85ae7cfe4dc2cc0b',
    messagingSenderId: '578948566482',
    projectId: 'kitahack2026-3d5f3',
    authDomain: 'kitahack2026-3d5f3.firebaseapp.com',
    storageBucket: 'kitahack2026-3d5f3.firebasestorage.app',
    measurementId: 'G-39RG8B0MVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD6WapB4_UF4TfrWGENiPRkWxMVZOEFn0',
    appId: '1:578948566482:android:0f3742bb9c2789e8c2cc0b',
    messagingSenderId: '578948566482',
    projectId: 'kitahack2026-3d5f3',
    storageBucket: 'kitahack2026-3d5f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlkArIJG34AiGOqxSLpmPz_f41h7KusVM',
    appId: '1:578948566482:ios:fa4708a0de66e7fac2cc0b',
    messagingSenderId: '578948566482',
    projectId: 'kitahack2026-3d5f3',
    storageBucket: 'kitahack2026-3d5f3.firebasestorage.app',
    iosBundleId: 'com.example.wasteSortingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlkArIJG34AiGOqxSLpmPz_f41h7KusVM',
    appId: '1:578948566482:ios:fa4708a0de66e7fac2cc0b',
    messagingSenderId: '578948566482',
    projectId: 'kitahack2026-3d5f3',
    storageBucket: 'kitahack2026-3d5f3.firebasestorage.app',
    iosBundleId: 'com.example.wasteSortingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCarS13SzWRFvXFoVGfMRCz8FAFu1m2XY',
    appId: '1:578948566482:web:6ace67b40b2fdf1fc2cc0b',
    messagingSenderId: '578948566482',
    projectId: 'kitahack2026-3d5f3',
    authDomain: 'kitahack2026-3d5f3.firebaseapp.com',
    storageBucket: 'kitahack2026-3d5f3.firebasestorage.app',
    measurementId: 'G-EX4QXV5JWP',
  );
}
